services:
  - type: web
    name: olympic-analytics
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: olympic_analytics_db
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: ML_MODEL_PATH
        value: ../ML/model.pkl
      - key: ML_ENCODERS_PATH
        value: ../ML/encoders.pkl